# Prefix for all records
epicsEnvSet("PREFIX", "13ZMQ1:")
# The port name for the detector
epicsEnvSet("PORT", "ZMQ1")
# The maximim image width; used to set the maximum size for this driver
# and for row profiles in the NDPluginStats plugin
epicsEnvSet("XSIZE",  "1024")
# The maximim image height; used to set the maximum size for this driver
# and for column profiles in the NDPluginStats plugin
epicsEnvSet("YSIZE",  "1024")
# The waveform is large enough for an image of size 1024x1024 of char type
epicsEnvSet("NELEMENTS", "1048576")

require "ADZMQ"

# Create an ADZMQ driver
runScript $(ADZMQ_DIR)/ZMQDriver.cmd,"ADZMQ_ADDR=tcp://127.0.0.1:5432"
# Create an NDZMQ plugin
runScript $(ADZMQ_DIR)/ZMQPlugin.cmd,"NDZMQ_ADDR=tcp://*:1234"
# common plugins
runScript $(ADCore_DIR)/commonPlugin.cmd
